export const users = [
  {
    id: 'Alice',
    name: 'Alice',
    friends: ['Bernou'],
    recommended: [
      {
        id: '1',
        name: 'Singing in the rain',
        category: 'Movie',
        platform: 'Home',
        recommendedBy: 'Bernou',
        rating: '9/10',
        comment: 'Old school ',
      },
      {
        id: '2',
        name: 'Walking dead',
        category: 'Serie',
        platform: 'Netflix',
        recommendedBy: 'Alice',
        rating: '8/10',
        comment: 'This is amazing',
      },
      {
        id: '3',
        name: 'Nelson Mandela Biography',
        category: 'Book',
        platform: 'Kobo',
        recommendedBy: 'Alice',
        rating: '10/10',
        comment: 'Recommend absolutely!!!',
      },
    ],
    recoNotSeen: [],
  },
  {
    id: 'Cha',
    name: 'Cha',
    friends: ['Alice'],
    recommended: [],
    recoNotSeen: [
      {
        id: '1',
        name: 'Singing in the rain',
        category: 'Movie',
        platform: 'Home',
        recommendedBy: 'Bernou',
        rating: '9/10',
        comment: 'Old school ',
      },
      {
        id: '2',
        name: 'Walking dead',
        category: 'Serie',
        platform: 'Netflix',
        recommendedBy: 'Alice',
        rating: '8/10',
        comment: 'This is amazing',
      },
      {
        id: '3',
        name: 'Nelson Mandela Biography',
        category: 'Book',
        platform: 'Kobo',
        recommendedBy: 'Alice',
        rating: '10/10',
        comment: 'Recommend absolutely!!!',
      },
    ],
  },
  {
    id: 'Margot',
    name: 'Margot',
    friends: ['Alice'],
    recommended: [],
    recoNotSeen: [
      {
        id: '1',
        name: 'Singing in the rain',
        category: 'Movie',
        platform: 'Home',
        recommendedBy: 'Bernou',
        rating: '9/10',
        comment: 'Old school ',
      },
      {
        id: '2',
        name: 'Walking dead',
        category: 'Serie',
        platform: 'Netflix',
        recommendedBy: 'Alice',
        rating: '8/10',
        comment: 'This is amazing',
      },
      {
        id: '3',
        name: 'Nelson Mandela Biography',
        category: 'Book',
        platform: 'Kobo',
        recommendedBy: 'Alice',
        rating: '10/10',
        comment: 'Recommend absolutely!!!',
      },
    ],
  },
  {
    id: 'Claire',
    name: 'Claire',
    friends: ['Alice'],
    recommended: [],
    recoNotSeen: [
      {
        id: '1',
        name: 'Singing in the rain',
        category: 'Movie',
        platform: 'Home',
        recommendedBy: 'Bernou',
        rating: '9/10',
        comment: 'Old school ',
      },
      {
        id: '2',
        name: 'Walking dead',
        category: 'Serie',
        platform: 'Netflix',
        recommendedBy: 'Alice',
        rating: '8/10',
        comment: 'This is amazing',
      },
      {
        id: '3',
        name: 'Nelson Mandela Biography',
        category: 'Book',
        platform: 'Kobo',
        recommendedBy: 'Alice',
        rating: '10/10',
        comment: 'Recommend absolutely!!!',
      },
    ],
  },
  {
    id: 'Bernou',
    name: 'Bernou',
    friends: ['Alice'],
    recommended: [
      {
        id: '1',
        name: 'Singing in the rain',
        category: 'Movie',
        platform: 'Home',
        recommendedBy: 'Bernou',
        rating: '9/10',
        comment: 'Old school ',
      },
      {
        id: '2',
        name: 'Walking dead',
        category: 'Serie',
        platform: 'Netflix',
        recommendedBy: 'Alice',
        rating: '8/10',
        comment: 'This is amazing',
      },
    ],
    recoNotSeen: [
      {
        id: '3',
        name: 'Nelson Mandela Biography',
        category: 'Book',
        platform: 'Kobo',
        recommendedBy: 'Alice',
        rating: '10/10',
        comment: 'Recommend absolutely!!!',
      },
    ],
  },
];
