export const users = [
  {
    id: 'Alice',
    name: 'Alice',
    friends: ['Cha', 'Margot', 'Claire', 'Bernou'],
    listRecommendations: [
      {
        id: '1',
        name: 'Singing in the rain',
        category: 'Movie',
        platform: 'Home',
        recommendedBy: 'Bernou',
        rating: '9/10',
        comment: 'Old school ',
        isChecked: false,
      },
      {
        id: '2',
        name: 'Walking dead',
        category: 'Serie',
        platform: 'Netflix',
        recommendedBy: 'Alice',
        rating: '8/10',
        comment: 'This is amazing',
        isChecked: true,
      },
      {
        id: '3',
        name: 'Nelson Mandela Biography',
        category: 'Book',
        platform: 'Kobo',
        recommendedBy: 'Alice',
        rating: '10/10',
        comment: 'Recommend absolutely!!!',
        isChecked: true,
      },
    ],
  },
  {
    id: 'Cha',
    name: 'Cha',
    friends: ['Alice', 'Margot', 'Claire', 'Bernou'],
    listRecommendations: [
      {
        id: '1',
        name: 'Singing in the rain',
        category: 'Movie',
        platform: 'Home',
        recommendedBy: 'Bernou',
        rating: '9/10',
        comment: 'Old school ',
        isChecked: false,
      },
      {
        id: '2',
        name: 'Walking dead',
        category: 'Serie',
        platform: 'Netflix',
        recommendedBy: 'Alice',
        rating: '8/10',
        comment: 'This is amazing',
        isChecked: false,
      },
      {
        id: '3',
        name: 'Nelson Mandela Biography',
        category: 'Book',
        platform: 'Kobo',
        recommendedBy: 'Alice',
        rating: '10/10',
        comment: 'Recommend absolutely!!!',
        isChecked: false,
      },
    ],
  },
  {
    id: 'Margot',
    name: 'Margot',
    friends: ['Alice', 'Cha', 'Claire', 'Bernou'],
    listRecommendations: [
      {
        id: '1',
        name: 'Singing in the rain',
        category: 'Movie',
        platform: 'Home',
        recommendedBy: 'Bernou',
        rating: '9/10',
        comment: 'Old school ',
        isChecked: false,
      },
      {
        id: '2',
        name: 'Walking dead',
        category: 'Serie',
        platform: 'Netflix',
        recommendedBy: 'Alice',
        rating: '8/10',
        comment: 'This is amazing',
        isChecked: false,
      },
      {
        id: '3',
        name: 'Nelson Mandela Biography',
        category: 'Book',
        platform: 'Kobo',
        recommendedBy: 'Alice',
        rating: '10/10',
        comment: 'Recommend absolutely!!!',
        isChecked: false,
      },
    ],
  },
  {
    id: 'Claire',
    name: 'Claire',
    friends: ['Alice', 'Cha', 'Margot', 'Bernou'],
    listRecommendations: [
      {
        id: '1',
        name: 'Singing in the rain',
        category: 'Movie',
        platform: 'Home',
        recommendedBy: 'Bernou',
        rating: '9/10',
        comment: 'Old school ',
        isChecked: false,
      },
      {
        id: '2',
        name: 'Walking dead',
        category: 'Serie',
        platform: 'Netflix',
        recommendedBy: 'Alice',
        rating: '8/10',
        comment: 'This is amazing',
        isChecked: false,
      },
      {
        id: '3',
        name: 'Nelson Mandela Biography',
        category: 'Book',
        platform: 'Kobo',
        recommendedBy: 'Alice',
        rating: '10/10',
        comment: 'Recommend absolutely!!!',
        isChecked: false,
      },
    ],
  },
  {
    id: 'Bernou',
    name: 'Bernou',
    friends: ['Alice', 'Cha', 'Margot', 'Claire'],
    listRecommendations: [
      {
        id: '1',
        name: 'Singing in the rain',
        category: 'Movie',
        platform: 'Home',
        recommendedBy: 'Bernou',
        rating: '9/10',
        comment: 'Old school ',
        isChecked: true,
      },
      {
        id: '2',
        name: 'Walking dead',
        category: 'Serie',
        platform: 'Netflix',
        recommendedBy: 'Alice',
        rating: '8/10',
        comment: 'This is amazing',
        isChecked: false,
      },
      {
        id: '3',
        name: 'Nelson Mandela Biography',
        category: 'Book',
        platform: 'Kobo',
        recommendedBy: 'Alice',
        rating: '10/10',
        comment: 'Recommend absolutely!!!',
        isChecked: true,
      },
    ],
  },
];
